apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "external-dns.fullname" . }}
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "external-dns.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "external-dns.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}