apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
type: Opaque
data:
  access-key: {{ .Values.userConfig.env.ak | b64enc | quote }}
  access-secret: {{ .Values.userConfig.env.sk | b64enc | quote }} 